packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@firebase/util': set this to true or false
  '@parcel/watcher': true
  '@swc/core': true
  core-js: false
  detox: true
  dtrace-provider: true
  esbuild: true
  nx: true
  protobufjs: set this to true or false
  sharp: true
  unrs-resolver: true
